### ISSUE TITLE
Error build android

### ISSUE THREAD

**Issue by khalisafkari** [pejonic/cordova-pejonic-plugin-exoplayer#1]
> * Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\Player.java:51: error: package com.Pejonic.tv does not exist
import com.Pejonic.tv.R;
                     ^
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\TrackSelectionHelper.java:30: error: package com.Pejonic.tv does not exist
import com.Pejonic.tv.R;
                     ^
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\Player.java:361: error: package R does not exist
        btn_settings.setImageResource(R.drawable.hplib_ic_settings);
                                       ^
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\Player.java:364: error: package R does not exist
        btn_settings.setId(R.id.exo_settings);
                            ^
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\Player.java:368: error: package R does not exist
        LinearLayout exo_buttons = mainLayout.findViewById(R.id.exo_buttons);
                                                            ^
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\Player.java:512: error: package R does not exist
            if(btn == R.id.exo_settings){
                       ^
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\TrackSelectionHelper.java:114: error: package R does not exist
    View view = inflater.inflate(R.layout.track_selection_dialog, null);
                                  ^
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\TrackSelectionHelper.java:115: error: package R does not exist
    ViewGroup root = view.findViewById(R.id.root);
                                        ^
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\TrackSelectionHelper.java:126: error: package R does not exist
    disableView.setText(R.string.selection_disabled);
                         ^
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\TrackSelectionHelper.java:135: error: package R does not exist
    defaultView.setText(R.string.selection_default);
                         ^
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\TrackSelectionHelper.java:138: error: package R does not exist
    root.addView(inflater.inflate(R.layout.list_divider, root, false));
                                   ^
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\TrackSelectionHelper.java:151: error: package R does not exist
          root.addView(inflater.inflate(R.layout.list_divider, root, false));
                                         ^
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\TrackSelectionHelper.java:178: error: package R does not exist
      enableRandomAdaptationView.setText(R.string.enable_random_adaptation);
                                          ^
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\TrackSelectionHelper.java:180: error: package R does not exist
      root.addView(inflater.inflate(R.layout.list_divider, root, false));
                                     ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
14 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by johnnwanosike1** [comment]
Remove "import com.Pejonic.tv.R;" and import your own R class to fix this error. 
Short cut key in android studio is Alt+Enter

**Comment by khalisafkari** [comment]
Work thanks 👍 , please add landscape orientation feature

**Comment by johnnwanosike1** [comment]
In the configuration you will find landscape

**Comment by johnnwanosike1** [comment]
You can us this https://cordova.apache.org/news/2017/03/30/screen-orientation-plugin.html
and remember to star my plugin. Thanks
