### ISSUE TITLE
error new version 2.5.9

### ISSUE THREAD

**Issue by khalisafkari** [pejonic/cordova-pejonic-plugin-exoplayer#2]
`Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\Player.java:359: error: package R does not exist
        btn_settings.setImageResource(R.drawable.hplib_ic_settings);
                                       ^
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\Player.java:362: error: package R does not exist
        btn_settings.setId(R.id.exo_settings);
                            ^
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\Player.java:366: error: package R does not exist
        LinearLayout exo_buttons = mainLayout.findViewById(R.id.exo_buttons);
                                                            ^
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\Player.java:510: error: package R does not exist
            if(btn == R.id.exo_settings){
                       ^
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\TrackSelectionHelper.java:112: error: package R does not exist
    View view = inflater.inflate(R.layout.track_selection_dialog, null);
                                  ^
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\TrackSelectionHelper.java:113: error: package R does not exist
    ViewGroup root = view.findViewById(R.id.root);
                                        ^
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\TrackSelectionHelper.java:124: error: package R does not exist
    disableView.setText(R.string.selection_disabled);
                         ^
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\TrackSelectionHelper.java:133: error: package R does not exist
    defaultView.setText(R.string.selection_default);
                         ^
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\TrackSelectionHelper.java:136: error: package R does not exist
    root.addView(inflater.inflate(R.layout.list_divider, root, false));
                                   ^
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\TrackSelectionHelper.java:149: error: package R does not exist
          root.addView(inflater.inflate(R.layout.list_divider, root, false));
                                         ^
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\TrackSelectionHelper.java:176: error: package R does not exist
      enableRandomAdaptationView.setText(R.string.enable_random_adaptation);
                                          ^
D:\Dev\Ionic\fbads\platforms\android\src\co\pejonic\cordova\plugin\exoplayer\TrackSelectionHelper.java:178: error: package R does not exist
      root.addView(inflater.inflate(R.layout.list_divider, root, false));
                                     ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
12 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.`

Please help

**Comment by johnnwanosike1** [comment]
Import R class to your project

**Comment by khalisafkari** [comment]
the controller does not appear on the touch `
  $scope.playVideo = function(){

    var successCallback = function(json) {

      alert(json);

      {
        'eventType':'TOUCH_EVENT',
        'eventAction':function(){
          window.ExoPlayer.showController();
        },
      }

    };

    var errorCallback = function(error) {
    };

    window.ExoPlayer.show(parameters, successCallback, errorCallback);

  }`

**Comment by johnnwanosike1** [comment]
The controller is only visible in the activity screen. But calling it with Java Script via Payload is not possible when playing video files but it visible with audio files.

**Comment by johnnwanosike1** [comment]
> `controller: { // If this object is not present controller will not be visible
>         streamImage: 'http://url.to/channel.png',
>         streamTitle: 'Cool channel / movie',
>         streamDescription: '2nd line you can use to display whatever you want like current program epg or movie description',
>         hideProgress: true, // Hide entire progress timebar
>         hidePosition: false, // If timebar is visible hide current position from it
>         hideDuration: false, // If timebar is visible Hide stream duration from it
>         controlIcons: {
>             'exo_rew': 'http://url.to/rew.png',
>             'exo_play': 'http://url.to/play.png',
>             'exo_pause': 'http://url.to/pause.png',
>             'exo_ffwd': 'http://url.to/ffwd.png'
>         }`
> 

This option is when you want to customize the buttons

**Comment by khalisafkari** [comment]
when i touch the screen the menu button does'nt show up

**Comment by johnnwanosike1** [comment]
Try this 
```
window.ExoPlayer.show(videoParams, function(success){
        //alert(JSON.stringify(success));

        if(success.eventType == 'START_EVENT'){

            screen.orientation.lock('landscape');
         }
        if(success.eventKeycode == 'KEYCODE_BACK'){
            window.ExoPlayer.close();
            screen.orientation.lock('portrait');
        }

        if(success.eventType == 'TOUCH_EVENT'){
            window.ExoPlayer.showController();
        }
    },
```

**Comment by johnnwanosike1** [comment]
Closing comment

**Comment by khalisafkari** [comment]
i will try

**Comment by johnnwanosike1** [comment]
OK, When you need any support write.

**Comment by pejonic** [comment]
#1
