### ISSUE TITLE
Error back 

### ISSUE THREAD

**Issue by khalisafkari** [pejonic/cordova-pejonic-plugin-exoplayer#3]
when calling back player and apps also come out

**Comment by johnnwanosike1** [comment]
let me get a screen shot

**Comment by khalisafkari** [comment]
Error Chek video [https://streamable.com/s/et6cs/gpwwmg](url)

**Comment by johnnwanosike1** [comment]
Is like the app closes automatically when playing video. That might be from your compilation, check your activity view. You are getting all right, just that you have to check if the activity view are correct. You can as well debug it.

**Comment by khalisafkari** [comment]
the app does not close itself while playing but the app will close when I press the back button

**Comment by johnnwanosike1** [comment]
That might be an error from you. The back button exit only the dialog screen of the player. That means that you have to check your code. Let me see your code?

**Comment by khalisafkari** [comment]
`$scope.playVideo = function(){


    //console.log(videoUrl);

    var parameters = {
        url: 'https://twist.moe/anime/3gatsunolions2/[HorribleSubs]%203-gatsu%20no%20Lion%20-%2023%20[1080p].mp4',
        aspectRatio: 'FILL_SCREEN',
        controller : {
          streamTitle: 'Streaming ',
         // streamDescription: '2nd line you can use to display whatever you want like current program epg or movie description',
          hideProgress: false, // Hide entire progress timebar
          hidePosition: false, // If timebar is visible hide current position from it
          hideDuration: false, // If timebar is visible Hide stream duration from it
            controlIcons: {
          }
        }
  };


    window.ExoPlayer.show(parameters, function(success){

        if(success.eventType == 'START_EVENT'){

            screen.orientation.lock('landscape');
         }
         
        if(success.eventKeycode == 'KEYCODE_BACK'){
            window.ExoPlayer.close();
            screen.orientation.lock('portrait');
        }

        if(success.eventType == 'TOUCH_EVENT'){
            window.ExoPlayer.showController();
        }

    }, function(error){
      console.log(error);
    })


  }
`

**Comment by johnnwanosike1** [comment]
Did u install orientation plugin?

**Comment by khalisafkari** [comment]
yes, i installed plugin screen orientation

**Comment by johnnwanosike1** [comment]
Use android studio debug mode to find the error or do this:

if(success.eventKeycode == 'KEYCODE_BACK'){
   alert("back button pressed");
       // window.ExoPlayer.close();
       // screen.orientation.lock('portrait');
    }

**Comment by khalisafkari** [comment]
i try result alert double show

**Comment by johnnwanosike1** [comment]
Check your code! Might be from it. Remove the plugin and reinstall it again. Debug the code using android studio.

**Comment by khalisafkari** [comment]
I have tried several times but the result remains the same,

You can directly try my code through ionic

code : [www.zip](https://github.com/pejonic/cordova-pejonic-plugin-exoplayer/files/1826696/www.zip)

**Comment by johnnwanosike1** [comment]
Delete the source. And send it via mail to me. Pejonic@gmail.com.

**Comment by khalisafkari** [comment]
i have send
